### PR TITLE
[small]adding-packaging

### PR DESCRIPTION
**Pull request by josdem**
- After run test cases we should build a `Jmetadata.zip` distribution for the final user
- Updating version

### CODE REVIEW

**Review by Lemeri123 — COMMENTED** [review]
Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project

**Comment by josdem** [comment]
Moving forward, in every build we will have an installation package for the final user as artifact, example: https://github.com/josdem/jmetadata/actions/runs/12470536207

**Comment by josdem** [comment]
> Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project

@Lemeri123 This package should include the LastFM secret and key, therefore it should bring metadata from LastFM and also you should be able to login to LastFM with your personal account, let me know if is not the case.

**Comment by josdem** [comment]
> > Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project
> 
> @Lemeri123 This package should include the LastFM secret and key, therefore it should bring metadata from LastFM and also you should be able to login to LastFM with your personal account, let me know if is not the case.

I notice I need a little change to make this work for the final user, I will do my best to do it today the sooner, tomorrow the latest.

**Comment by josdem** [comment]
> > > Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project
> > 
> > 
> > @Lemeri123 This package should include the LastFM secret and key, therefore it should bring metadata from LastFM and also you should be able to login to LastFM with your personal account, let me know if is not the case.
> 
> I noticed I need a little change to make this work for the final user, I will do my best to do it today the sooner, tomorrow the latest.

**Comment by Lemeri123** [comment]
I tried but when I try logging in, it displays an error in the terminal about the LASTFM_API_KEY

**Comment by Lemeri123** [comment]
> > > Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project
> > 
> > 
> > @Lemeri123 This package should include the LastFM secret and key, therefore it should bring metadata from LastFM and also you should be able to login to LastFM with your personal account, let me know if is not the case.
> 
> I notice I need a little change to make this work for the final user, I will do my best to do it today the sooner, tomorrow the latest.

okay then @josdem you keep me posted on how it goes

**Comment by josdem** [comment]
> > > > Looks good to me because the Gradle distZip task is correctly configured to produce a distributable .zip file for the project
> > > 
> > > 
> > > @Lemeri123 This package should include the LastFM secret and key, therefore it should bring metadata from LastFM and also you should be able to login to LastFM with your personal account, let me know if is not the case.
> > 
> > 
> > I notice I need a little change to make this work for the final user, I will do my best to do it today the sooner, tomorrow the latest.
> 
> okay then @josdem you keep me posted on how it goes

Hi @Lemeri123 please try again, I am unsure if this is the best way to store the key and secret, most likely not, but it is working, if you want to see where I get the information to do it please take a look at this: https://github.com/orgs/community/discussions/68857

I was able to login to LastFM with my personal account, please download and try with this build: https://github.com/josdem/jmetadata/actions/runs/12473719581

I am adding an album I was using for testing lastFM metadata completion, let me know if it is not working for you.
https://drive.google.com/file/d/1wB4ESY8RgUoA54ovG-k594flDsiZOYvN/view?usp=sharing

**Screenshot**
lastFM

**Pull request merged**
